package com.campusfit.modules.post.vo;

public record PostCardVO(
    String id,
    Long authorId,
    String coverTag,
    String title,
    String subtitle,
    String desc,
    String coverImageUrl,
    String user,
    String avatar,
    String avatarUrl,
    String avatarClass,
    String school,
    String scene,
    String style,
    String budget,
    int likes,
    int comments,
    int saves,
    int shares,
    String price,
    String product,
    String platform,
    String profit,
    String guideTip,
    String publishStatus,
    String publishStatusText,
    String publishStatusDesc,
    boolean canViewDetail,
    boolean canShelfDown,
    boolean canRestore
) {
}
