spring:
  sql:
    init:
      mode: ${SQL_INIT_MODE:never}
      encoding: UTF-8
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

app:
  env: dev
  cors:
    allowed-origins: '*'
